name: powder_pilot
description: "The best Ski Tracker."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^5.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  latlong2: ^0.9.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  flutter_map_animations: ^0.5.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  flutter_polyline_points: ^2.0.0
  app_settings: ^5.1.1
  fl_chart: ^0.66.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  country_flags: ^2.2.0

  # flutter pub run intl_translation:generate_from_arb --output-dir=lib/l10n lib/color.dart lib/l10n/intl_*.arb
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.19.0


# Dependency overrides
dependency_overrides:
  geolocator_android:
    git:
      url: https://github.com/Wackymax/flutter-geolocator.git
      path: geolocator_android
      ref: 135277e44e8283bae5473691324405fe360c844e


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_1024.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon_1024_padding.png"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#dbdbe5"
  image: assets/images/icon_1024.png

  android_12:
    icon_background_color: "#dbdbe5"
    image: assets/images/icon_1024_padding.png

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    - assets/images/icon_256.png
    - assets/images/background.png
    - assets/images/welcome_pages/finish.png
    - assets/images/welcome_pages/location.png
    - assets/images/lift/chair_lift.png
    - assets/images/lift/gondola.png
    - assets/images/welcome_pages/slope_info.png
    - assets/images/welcome_pages/stats.png
    - assets/images/welcome_pages/activity.png
    - assets/images/welcome_pages/battery_optimization.png
    - assets/legal/terms_of_service.txt
    - assets/legal/privacy_policy.txt
    - lib/l10n/intl_en.arb
    - lib/l10n/intl_de.arb

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
